### ISSUE TITLE
No exported ometiff and frozen progress

### ISSUE THREAD

**Issue by rjesud** [NHPatterson/wsireg#17]
* wsireg version: 0.2.1 (installed via pip)
* Python version: 3.7
* Operating System: Linux (16cores, 128GB RAM)

### Description

I would like to register 2 sequentially stained IF WSI ometiff images (same section- 6plex and 5plex). Both images have a DAPI channel which I would like to use as the "linking" channel. 

I followed the example workflow on github. It appears that the project folder populates with data (yaml files, iteration and transform text files) and but **I do not get any ometiff export. The process has been running overnight with no apparent progress.** 

### What I Did

```
from wsireg.wsireg2d import WsiReg2D
import os

os.chdir('/blah/ometiff_imagefolder/')

# initialize registration graph
reg_graph = WsiReg2D("my_reg_project", "./project_folder2")

# add registration images (modalities)
reg_graph.add_modality(
    "modality_fl1",
    "IF1.ome.tiff",
    image_res=0.325,
    channel_names=["DAPI", "FITC", "Cy3","Cy5","Cy7","CFP"],
    channel_colors=["blue", "green", "red","yellow","purple","orange"],
    prepro_dict={
        "image_type": "FL",
        "ch_indices": [0],
        "as_uint8": True,
        "contrast_enhance": True,
    },
)

reg_graph.add_modality(
    "modality_fl2",
    "IF2.ome.tiff",
    image_res=0.325,
    channel_names=["DAPI", "FITC", "Cy3","Cy5","CFP"],
    channel_colors=["blue", "green", "red","yellow","purple"],
    prepro_dict={
        "image_type": "FL",
        "ch_indices": [0],
        "as_uint8": True,
        "contrast_enhance": True,
    },
)
reg_graph.add_reg_path(
    "modality_fl1",
    "modality_fl2",
    thru_modality=None,
    reg_params=["affine"],
)

reg_graph.register_images()
reg_graph.save_transformations()
reg_graph.transform_images(file_writer="ome.tiff")
```

It appears to be stuck here:
![image](https://user-images.githubusercontent.com/46010245/131900290-a2bfd8a0-895a-4cae-9204-9a4b724c1af7.png)

output so far:
![image](https://user-images.githubusercontent.com/46010245/131900422-0218471b-85e8-438c-975b-aa87d3d079e9.png)

![image](https://user-images.githubusercontent.com/46010245/131900462-33df9931-c8f8-4ea8-95b3-6ed5a5907dcd.png)

**Comment by NHPatterson** [comment]
I am guessing there was a segmentation fault in `elastix` during the run (a catastrophic error). Sometimes this can hang indefinitely with no indication of why!
The default "affine" registration parameters uses 10 resolutions so you should see 10 `IterationInfo` and `TransformParameters` files in a completed run and here there are only 4.  There is a random element to this fault in my experience. The only other thing I would consider is a memory issue but at 128 GB you are probably ok but it may be worth checking. In order for this registration to run, one whole plane of your WSI is loaded into memory and cast to float32(4 bytes per px) and pyramidalized. This can eat up some memory.

 My suggestion is try to run it again! Also, I would suggestion using `["rigid","affine"]` as registration parameters. It really doesn't add much time and safeguards against bad shearing that may occur from affine when the images aren't well aligned initially. 

Let me know where you get, could you also get the dimension of your images in pixels?

**Comment by rjesud** [comment]
Thanks for the input. Unfortunately, no luck with several attempts using `["rigid","affine"]`. It appears to always stall at 4 resolutions. The images are quite big 19GB (46147x46135) and 15GB (44310x46136). They each have 7 pyramid levels. Pixel type is unit16 and resolution is 0.3250um/pixel. 

I also tried installing wsireg directly from the github repo. I receive this error when executing registration:
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/local/10316429/ipykernel_31454/435754824.py in <module>
      6 )
      7 
----> 8 reg_graph.register_images()
      9 reg_graph.save_transformations()
     10 reg_graph.transform_images(file_writer="ome.tiff")

~/.conda/envs/wsireg2/lib/python3.7/site-packages/wsireg/wsireg2d.py in register_images(self, parallel)
    651                 )
    652 
--> 653                 src_reg_image.read_reg_image()
    654                 tgt_reg_image.read_reg_image()
    655                 if (

~/.conda/envs/wsireg2/lib/python3.7/site-packages/wsireg/reg_images/np_reg_image.py in read_reg_image(self)
     65 
     66         image = read_preprocess_array(
---> 67             self.image, preprocessing=self.preprocessing, force_rgb=self.is_rgb
     68         )
     69 

~/.conda/envs/wsireg2/lib/python3.7/site-packages/wsireg/utils/im_utils.py in read_preprocess_array(img, preprocessing, force_rgb)
    124             ):
    125                 chs = tuple(preprocessing.get('ch_indices'))
--> 126                 img = img[chs, :, :]
    127 
    128         image = sitk.GetImageFromArray(np.squeeze(np.asarray(img)))

~/.conda/envs/wsireg2/lib/python3.7/site-packages/dask/array/core.py in __getitem__(self, index)
   1728         )
   1729 
-> 1730         index2 = normalize_index(index, self.shape)
   1731         dependencies = {self.name}
   1732         for i in index2:

~/.conda/envs/wsireg2/lib/python3.7/site-packages/dask/array/slicing.py in normalize_index(idx, shape)
    910     for i, d in zip(idx, none_shape):
    911         if d is not None:
--> 912             check_index(i, d)
    913     idx = tuple(map(sanitize_index, idx))
    914     idx = tuple(map(normalize_slice, idx, none_shape))

~/.conda/envs/wsireg2/lib/python3.7/site-packages/dask/array/slicing.py in check_index(ind, dimension)
    979         return
    980 
--> 981     elif ind >= dimension:
    982         raise IndexError(
    983             "Index is not smaller than dimension %d >= %d" % (ind, dimension)

TypeError: '>=' not supported between instances of 'tuple' and 'int'`

**Comment by NHPatterson** [comment]
This is strange because you have adequate memory to support images of that size. Have you tried running outside of a Jupyter Notebook? `elastix` prints a lot to console and perhaps there is an error there that is being supressed in the JN. Another thing to try is to delete the `.imcache` folder when you rerun. This stores the "preprocessed" versions of the images so that if you tweak registration parameters you can quickly reload the image. Can you share the images somehow? `wsireg` is fairly new and I'm just now starting to see use from others. Thanks for helping me sort this out.

**Comment by NHPatterson** [comment]
@rjesud Hello, if you pull down the latest version from git the error you encounter is fixed. I wonder if you ever made any more progress otherwise? -Heath

**Comment by rjesud** [comment]
Hi Heath, Thanks and sorry for the delayed response. I will run the latest version and circle back with you.

**Comment by rjesud** [comment]
Hi Heath, I'm happy to report that I was able to execute the code successfully. I used the latest version from git and I also ran the script outside of jupyter notebook as originally suggested. Thanks for your help on this issue!

**Comment by NHPatterson** [comment]
No problem.. really happy it executed, now I hope your images are well registered too 👍. 

May I suggest you try another feature of the library which may be appropriate? `WsiReg2D` has a method called `add_merge_modalities` which essentially will write your fluorescence images to a single OME-TIFF file rather than separate files. Essentially your channel names will be prepended with the `modality_tag`  in the OME-TIFF so the first image would have channel names like "modality_fl1 - DAPI",  "modality_fl1 - FITC", etc. This helps for visualization on some platforms such as if you want to do color blending of registered modalities in QuPath, but may create a mega OME-TIFF. 

From your previous script:
```python
from wsireg.wsireg2d import WsiReg2D
import os

os.chdir('/blah/ometiff_imagefolder/')

# initialize registration graph
reg_graph = WsiReg2D("my_reg_project", "./project_folder2")

# add registration images (modalities)
reg_graph.add_modality(
    "modality_fl1",
    "IF1.ome.tiff",
    image_res=0.325,
    channel_names=["DAPI", "FITC", "Cy3","Cy5","Cy7","CFP"],
    channel_colors=["blue", "green", "red","yellow","purple","orange"],
    prepro_dict={
        "image_type": "FL",
        "ch_indices": [0],
        "as_uint8": True,
        "contrast_enhance": True,
    },
)

reg_graph.add_modality(
    "modality_fl2",
    "IF2.ome.tiff",
    image_res=0.325,
    channel_names=["DAPI", "FITC", "Cy3","Cy5","CFP"],
    channel_colors=["blue", "green", "red","yellow","purple"],
    prepro_dict={
        "image_type": "FL",
        "ch_indices": [0],
        "as_uint8": True,
        "contrast_enhance": True,
    },
)
reg_graph.add_reg_path(
    "modality_fl1",
    "modality_fl2",
    thru_modality=None,
    reg_params=["affine"],
)

# merge these modalities to a single OME-TIFF
# merge name will be in the final OME-TIFF file name
reg_graph.add_merge_modalities("multicycle",["modality_fl1","modality_fl2"])

reg_graph.register_images()
reg_graph.save_transformations()
reg_graph.transform_images(file_writer="ome.tiff")
```

**Comment by rjesud** [comment]
Hi again, Unfortunately, the addition of this `add_merge_modalities` resulted in this error:

`Traceback (most recent call last):
  File "/gstore/home/jesudasr/.conda/envs/wsireg/lib/python3.7/site-packages/wsireg/wsireg2d.py", line 922, in _transform_write_merge_images
    final_modalities.append(self.reg_paths[sub_image][-1])
KeyError: 'modality_fl2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wsireg1.py", line 49, in <module>
    reg_graph.transform_images(file_writer="ome.tiff")
  File "/gstore/home/jesudasr/.conda/envs/wsireg/lib/python3.7/site-packages/wsireg/wsireg2d.py", line 1058, in transform_images
    to_original_size=to_original_size
  File "/gstore/home/jesudasr/.conda/envs/wsireg/lib/python3.7/site-packages/wsireg/wsireg2d.py", line 928, in _transform_write_merge_images
    RegTransform(t) for t in initial_transforms
TypeError: 'NoneType' object is not iterable
`

**Comment by NHPatterson** [comment]
Yes there was an error that I didn't find in testing. I've fixed this I believe. Can you try again?

**Comment by rjesud** [comment]
Thanks! I can confirm the issue is resolved. I will also say the registration is beautiful. A follow up question on usage

1) If I do not include `reg_graph.add_merge_modalities("multicycle",["modality_fl1","modality_fl2"])` it appears it will default to per wsi? Is it possible to export both merged and per wsi?
2) Regarding RGB+IF merge - we have actually worked with these types of images from another software and it was an extremely useful tool. Pathologists in particular like it since they are used to working with H&E but now the data is "augmented" with molecular info from the IF. Here is an example of such images in OMERO:
![image](https://user-images.githubusercontent.com/46010245/133672344-27bd57d0-d5e4-4b55-a94d-a3c769511f9f.png)
The RGB channels are written into the file as grayscale channels which we simply assign IF pseudo colors of RGB respectively. I suppose they have to do some dtype conversion to get things to work.

**Comment by NHPatterson** [comment]
Right now there is no option to export both, but I can probably get it in and merged quickly.

For #2..this is more complicated. I have a thought on how it could be done, but I can't put it in the API quickly. I'll try to write a script for you various parts of the library in the mean time.

**Comment by rjesud** [comment]
Thanks, Heath. So, currently, if a 3 image registration is run with IF and BF included and `reg_graph.add_merge_modalities("multicycle",["modality_fl1","modality_fl2"])` is called, will it output the merged for IF images then a separate image for the BF?

**Comment by NHPatterson** [comment]
Yep. Internally there is a list of all modalities, anything that is within a merge gets pruned from that list and not written individually. I will put in a fix to output both merged and individual tomorrow.

**Comment by NHPatterson** [comment]
@rjesud This is fixed with the latest update. You can pull it down from git. I'll make a deployment to pypi (pip) soon. 

You will just need to add an argument like below
```python
reg_graph.transform_images(file_writer="ome.tiff", remove_merged=False)
```

This will output any merged images as well as each modality individually.

**Comment by rjesud** [comment]
Awesome! I will give it a try!
