### ISSUE TITLE
error calling wsi-reg on napari on windows

### ISSUE THREAD

**Issue by alcrevenna** [NHPatterson/wsireg#58]
* wsireg version:
* Python version: 3.9
* Operating System: windows

### Description

I just did a fresh install on windows, used my anaconda prompt to create an env, pip install and everything went fine.
I opened napari and then called the wsi-reg plugin, I get this error:

### What I Did

```
ImportError: DLL load failed while importing _ITKCommonPython: The specified module could not be found.

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
RuntimeError: Failed to import command at 'napari_wsireg._widget:WsiReg2DMain': DLL load failed while importing _ITKCommonPython: The specified module could not be found.
```
any ideas is appreciated
best,
Alvaro

**Comment by NHPatterson** [comment]
This is related to `ITKElastix` and an install error, see issue here --> https://github.com/InsightSoftwareConsortium/ITKElastix/issues/154

Could you try this in in your environment:

```bash
pip uninstall itk
pip uninstall itk-elastix
pip install --pre itk-elastix
```

and let me know if it works. I've seen this error before, but I have also created new environments and it doesn't occur.
