### ISSUE TITLE
PyCapsule_Import "_ITKCommonPython._C_API" is not valid

### ISSUE THREAD

**Issue by BioinfoTongLI** [NHPatterson/wsireg#59]
* wsireg version: 0.3.6
* Python version: 3.9
* Operating System: Ubuntu 20.04

### Description

Hi there, I am trying to run the demo script with my own data in a Docker container. Here's the image definition

### What I Did

```
FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends procps ffmpeg libsm6 libxext6 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN python3 -m pip install --upgrade pip wsireg fire dask_image --no-cache-dir
```

I've added the images as in the demo script. Then when it comes to this step.
```
    reg_graph.register_images()
```
it showed:
```    File "/usr/local/lib/python3.9/site-packages/wsireg/wsireg2d.py", line 780, in register_images
      reg_tforms = register_2d_images_itkelx(
    File "/usr/local/lib/python3.9/site-packages/wsireg/utils/reg_utils.py", line 182, in register_2d_images_itkelx
      selx = itk.ElastixRegistrationMethod.New(
    File "/usr/local/lib/python3.9/site-packages/itk/support/lazy.py", line 138, in __getattribute__
      base.itk_load_swig_module(module, namespace)
    File "/usr/local/lib/python3.9/site-packages/itk/support/base.py", line 132, in itk_load_swig_module
      l_module = loader.load(swig_module_name)
    File "/usr/local/lib/python3.9/site-packages/itk/support/base.py", line 291, in load
      l_spec.loader.exec_module(l_module)  # pytype: disable=attribute-error
    File "<frozen importlib._bootstrap_external>", line 850, in exec_module
    File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
    File "/usr/local/lib/python3.9/site-packages/itk/support/../ElastixPython.py", line 13, in <module>
      from . import _ElastixPython
  AttributeError: PyCapsule_Import "_ITKCommonPython._C_API" is not valid
```
Any help would be really appreciated!

Best,
Tong

**Comment by NHPatterson** [comment]
@BioinfoTongLI 

Thanks for sharing your docker set up, really cool! This issue is related to ITKElastix and ITK python and similar issues have been raised on their respective repos. What I think may work is to install a previous version of ITKElastix before installing wsireg: 

```bash
pip install itk-elastix==0.13.0
pip install wsireg
```
or for the docker maybe try:
```bash
RUN python3 -m pip install --upgrade pip itk-elastix==0.13.0 wsireg fire dask_image --no-cache-dir
```

I never saw installation issues with the previous `itk-elastix`.

**Comment by NHPatterson** [comment]
according to https://github.com/InsightSoftwareConsortium/ITKElastix/issues/159#issuecomment-1206416873 you can also try:

```
RUN python3 -m pip install --upgrade pip itk==v5.3rc04.post1 wsireg fire dask_image --no-cache-dir
```

**Comment by BioinfoTongLI** [comment]
Hi @NHPatterson Thanks for your prompt answers!

Unfortunately, I've tested 0.13.0 and 0.12.0, none seem to work

And just tried the lastest as well (replace `itk==v5.3rc04.post1` by `itk==v5.3rc04.post2`, since `post1` is missing with my `pip`)

> `RUN python3 -m pip install --upgrade pip itk==v5.3rc04.post2 wsireg fire dask_image --no-cache-dir`

Still no luck, alwasy the same error :(
I will keep an eye on the official repo as well, thanks for the link!

Best,
Tong

**Comment by BioinfoTongLI** [comment]
[This](https://github.com/InsightSoftwareConsortium/ITKElastix/issues/159#issuecomment-1216978998) solved this issue. Closing this for now! Thanks @NHPatterson for helping!
