### ISSUE TITLE
Copy wsireg alignment scheme to rest of the channels from same modality?

### ISSUE THREAD

**Issue by BokaiZhu** [NHPatterson/wsireg#62]
Hi wsireg team,

Thanks for providing this excellent tool! I'm trying to align images between two modalities: 1) target modality of H&E staining. 2) moving modality of multiplex IF (channels already aligned within this modality). I'm currently using napari-wsireg to align DAPI channel in modality 2 -> H&E modality 1. napari-wsireg works well in this case. However, I wonder if there is a way to output the alignment transformation from DAPI -> H&E, and use the same exact transformation schemes onto the rest of the channels in modality 2?

I understand I can align DAPI -> H&E, then other mIF channels -> DAPI to achieve the same thing, but I wonder if I can directly copy the transformation in the first step to the other channels, as channels within modality 2 are already aligned. Thank you for the help in advance!

Detailed information:

* wsireg version:  napari-wsi
* Python version: 3.9
* Operating System: mac

**Comment by NHPatterson** [comment]
@BokaiZhu This is definitely doable! This is the concept of an "attachment image". In wsireg you can click the + Attachment button to add it:
<img width="595" alt="image" src="https://user-images.githubusercontent.com/17855764/195334397-ae584e00-12ec-4ed3-b05d-3912cf02bcdc.png">

This will prompt you to load an image, but also select which modality it attaches to.. so you should det up your DAPI to HE =, then attach the mIF image to the DAPI using the "+ Attachment" option. 

Attachments are modalities that are already registered to an existing one, so they are transformed along the same path as the image to which it is attached, but not used in registration, your exact case!

Hope this helps, let me know if you encounter any trouble.

Heath

**Comment by BokaiZhu** [comment]
Hi Heath,

Thank you so much for the prompt response!! I will try this and let you now if I pump into more questions in the future.

Bokai
