### ISSUE TITLE
register_images() hangs when calling UpdateLargestPossibleRegion()

### ISSUE THREAD

**Issue by conradfoo** [NHPatterson/wsireg#63]
* wsireg version: 0.3.8
* Python version: 3.10.8
* Operating System: Linux CentOS 7

### Description

I am trying to align two images using the WsiReg2D pipeline object. However, after adding images and running the registration, the `register_images()` function hangs when running `UpdateLargestPossibleRegion()`.

### What I Did

Basically, I just loaded 2 numpy arrays (3000x2000ish resolution) and tried to run register_images(). If I comment out `selx.UpdateLargestPossibleRegion()`, I am able to get the resulting transform parameters and transformed image. The transformed image is not aligned to the fixed coordinate system (because the region was not updated). 

There are no errors thrown; the program simply does not continue after running the region update. I have left it running over the course of 2 days with no successful resolution; the registration process itself takes ~20s. I've attached a log (the program hangs after the last line), as well as the project configuration.

Thanks!

[wsi.txt](https://github.com/NHPatterson/wsireg/files/11312803/wsi.txt)
[20230424-093605-test_project-configuration-setup.txt](https://github.com/NHPatterson/wsireg/files/11312805/20230424-093605-test_project-configuration-setup.txt)

**Comment by NHPatterson** [comment]
Ok. I'm not sure what the error is and not sure I can figure it out from your message. What is the dtype of your numpy arrays? If you can, can you save and share the numpy arrays? I can keep them confidential. 

```python
np.save("array1.npy", array1)
np.save("array2.npy", array2)
```

**Comment by conradfoo** [comment]
OK I think I realize the issue - I rotated one of the images (which converted the image from uint16 -> float64) to test the registration. When I changed it back to uint16, there were no issues. Thanks! (Here are the images in case you wanted to look, but I suspect it won't be necessary.)
[image_npy.zip](https://github.com/NHPatterson/wsireg/files/11313521/image_npy.zip)

**Comment by NHPatterson** [comment]
Glad it worked out easily. It's good for me to know float64 doesn't work but I don't think I can fix that because it's an ITK issue. You can preprocess rotations in wsireg prior to running the automated alignment using `preprocessing`. This has an advantage in that your wsireg transform contains all spatial transformations. See example below on how to add.

```python
reg_graph.add_modality(
    "modality_fluo",
    "./data/im1.tiff",
    image_res=0.65,
    channel_names=["DAPI", "eGFP", "DsRed"],
    channel_colors=["blue", "green", "red"],
    preprocessing={
        "image_type": "FL",
        "ch_indices": [1],
        "as_uint8": True,
        "contrast_enhance": True,
        # rotation counter-clockwise in degrees
        "rot_cc":90,
        # flip --> h or v
        "flip": "h"
    },
)
```
